spring:
  application:
    name: tipton-reservations
  data:
    mongodb:
      uri: mongodb+srv://administrator:YbHidL31.5.1@tiptonreservations.hqk4yh5.mongodb.net/tipton?appName=TiptonReservations
  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.security: DEBUG
