spring:
  application:
    name: tipton-reservations
  data:
    mongodb:
      uri: ${MONGODB_URI}
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: https://dsl77ny0dhn06.cloudfront.net/api/login/oauth2/code/google

logging:
  level:
    org.springframework.security: DEBUG

tipton:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000 # 24 hours in milliseconds

stripe:
  api:
    key: ${STRIPE_SECRET_KEY:default_key}

server:
  port: 5000
  servlet:
    context-path: /api
