spring:
  application:
    name: tipton-reservations
  data:
    mongodb:
      uri: mongodb+srv://administrator:YbHidL31.5.1@tiptonreservations.hqk4yh5.mongodb.net/tipton?appName=TiptonReservations
  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.security: DEBUG

tipton:
  app:
    jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    jwtExpirationMs: 86400000 # 24 hours in milliseconds

server:
  port: 8080